server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/studentsystem?characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    encoding: UTF-8


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pojo
logging:
  level:
    root: info
    com: debug
    level:
      org.apache.tomcat: DEBUG
      org.apache.catalina: DEBUG